using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static threeemonthCsharp.Device;

namespace threeemonthCsharp
{
    internal class Program
    {
        static void Main(string[] args)
        {
            //Conditional conditional = new Conditional();
            //Console.WriteLine("Enter a number");
            //int number = int.Parse(Console.ReadLine());
            //string paramvalue=conditional.ParamType(number);
            //Console.WriteLine($"Type of number:{paramvalue}");
            //string evenodd = conditional.evenOddNumber(number);
            //Console.WriteLine($"Number is:{evenodd}");
            //Console.WriteLine("Enter string");
            //string value= null;
            //string Coalescingvalue = conditional.Coalescing(value);
            //Console.WriteLine($"value:{Coalescingvalue}");
            //Console.WriteLine("Enter a day number");
            //int daynum = int.Parse(Console.ReadLine());
            //string dayname = conditional.nameofDays(daynum);
            //Console.WriteLine($"Day name:{dayname}");
            //Common common = new Common();
            ////common.name=dayname;
            //string name=common?.name ?? "no name";
            //Console.WriteLine($"Value:{name}");
            //loop loop = new loop();
            //loop.EvenNumber();
            //Console.WriteLine("enter number");
            //int a = int.Parse(Console.ReadLine());
            //loop.SumNumb(a);
            //Console.WriteLine("please enter password");
            //string pass=Console.ReadLine();
            //loop.correctPassword(pass);
            //loop.Reverse();
            //loop.OddNumber();
            //loop.Multiplication();
            //loop.sumofnumb();
            //loop.ReverseFor();
            //loop.Factorialnum();
            //loop.Stringname();
            //loop.Evennumb();
            //loop.PrintChar();
            //loop.PrintCountry();
            //loop.SquareNumb();
            //loop.Addednumber();
            //loop.AddednumberList();
            //loop.Printnumb();
            //function function = new function();
            //Console.WriteLine("Enter the name");
            //string name = Console.ReadLine();
            //function.welcome(name);
            //Console.WriteLine("enter numbers");
            //int a = int.Parse(Console.ReadLine());
            //int b = int.Parse(Console.ReadLine());
            //function.Multiply(a,b);
            //int[] num = {1,1,2 ,2};
            //function.UseParams(num);
            //Console.WriteLine("enter number");
            //int a = int.Parse(Console.ReadLine());
            //int cube =function.cubenum(a);
            //Console.WriteLine($"Cube of number:{cube}");
            //string value=function.GetStatus(a);
            //Console.WriteLine($"student is :{value}");
            //bool value = function.Evennumber(a);
            //Console.WriteLine($"{value}");
            //function.Greet();
            //string names=function.Greet(name);
            //Console.WriteLine($"Hello:{names}");
            //int mul = function.Multiplication(a,b);
            //double multi = function.Multiplication(3.00,4.00);
            //Console.WriteLine($"multiplication:{mul}");
            //Console.WriteLine($"multiplication:{multi}");
            //function.DisplayInfo("Sweta");
            //function.DisplayInfo("Sweta",20);
            //function.DisplayInfo(20,"Sweta");
            // Arrays arrays=new Arrays();
            //arrays.OneDArray();
            //arrays.Eyenlist();
            //arrays.Average();
            //arrays.ReplaceElement();
            //arrays.Student();
            //arrays.JaggedMonths();
            //arrays.Transpose();
            //arrays.SumItem();
            //arrays.countryname();
            //arrays.Studentlist();
            //arrays.Students();
            //Student student=new Student();
            //student.Name="Sweta";
            //arrays.DisplayInfo(student.Name);
            //Car car=new Car();
            //Car car1=new Car();
            //arrays.ShowCarInfo(car.Brand="Maruti",car.Model="2345",car.Year="2025");
            //arrays.ShowCarInfo(car1.Brand="Kia",car1.Model="34677",car1.Year="2024");
            //Calculator calculator = new Calculator();
            //calculator.Cal();
            //Cars cars = new Cars();
            //cars.Brand="Maruti";
            //cars.Start();
            //cars.Drive();
            //Laptop laptop = new Laptop();
            //laptop.display();
            //laptop.Boot();
            //laptop.Openid();
            //Students student = new Students();
            //student.Introduce();
            //student.Study();

            //Teacher teacher = new Teacher();
            //teacher.Introduce();
            //teacher.Teach();
            //Author author = new Author();
            //author.Write();
            //author.read();
            //Manager manager = new Manager();
            //manager.Per();
            //manager.Speak();
            //manager.Manage();
            //manager.Empl();
            //Shape shape = new Shape();
            //shape.area(3);
            //shape.area(3,5);
            //shape.area(2.2f);
            //Vehicle vehicle = new Truck();
            //Vehicle vehicles = new Bus();
            //    vehicle.drive();
            //vehicles.drive();
            //Vehicle vehicle1 = new Vehicle();
            //vehicle1.drive();
            //BankAccount bankAccount = new BankAccount("21212121212");
            //bankAccount.Balance=12345;

            //Console.WriteLine(bankAccount.Balance);
            //Console.WriteLine(bankAccount.AccountNumber);
            //INotification notification = new EmailNotification();
            //notification.Send("Sweta","Sending email to ");
            //notification.Cancel("invalid password");
            //INotification notifications = new SMSlNotification();
            //notification.Send("Richa", "Sending SMS to ");
            //notification.Cancel("invalid username");
            //INotification notify= new PushNotification();
            //notify.Send("Abhay", "Sending SMS to ");
            //notify.Cancel("invalid credential");
            //Collections collections = new Collections();
            //collections.color();
            //collections.rollnumber();
            //collections.ticketcounter();
            //collections.booktitle();
            //stringhandling stringhandling = new stringhandling();
            //stringhandling.replace();
            //contactmanager contactmanager = new contactmanager();
            //contactmanager.contact();
            //validate validate = new validate();
            //validate.ValidateAge();
            //validate.calculator();
            //validate.Withdrw();
            //InputOutputFile inputOutputFile = new InputOutputFile();
            //inputOutputFile.InputOutputFiles();
            //inputOutputFile.ReadFile();
            //inputOutputFile.CommentReadWrite();
            //Delegate d = new Delegate();
            //MathOperation mathOperation = d.Add;
            //mathOperation(10,20);
            //MathOperation mathsub = d.Sub;
            //mathsub(10, 20);
            //MathOperation mathmul = d.Mul;
            //mathmul(10, 20);

            //MathOperation mathdiv = d.Div;
            //mathdiv(10, 20);
            //Linq linq = new Linq();
            //linq.StudName();
            //linq.AverageMark();
            //linq.highestmark();
            //linq.Lowestmark();
            //linq.Countstudent();
            //linq.Mark();
            //linq.Letter();
            //linq.Highmark();
            //asyncawait asyncawait = new asyncawait();
            //asyncawait.Method();
            //asyncawait.Methods();
            Console.ReadKey();

            
        }
        
    }
}
